---
# Actions that will be run on all nodes.
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags: common

- name: Create personal user
  user:
    name: "{{ username }}"
    groups: adm, wheel
    state: present
  tags: common

- name: Set authorized key for personal user
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', '../files/indimatch.pub')}}"
    state: present
  tags: common
    
- name: Set empty password for personal user
  command: passwd -d "{{ username }}"
  tags: common
  
- name: Update system packages
  yum:
    name: '*'
    state: latest
  tags: common